swagger: '2.0'
info:
  description: Finance management sysytem
  version: 1.0.0
  title: Grants Information Management System
  termsOfService: 'http://kefinance.clintonhealthaccess.org/terms/'
  contact:
    email: mwangikevinn@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8000'
basePath: /api
tags:
  - name: Approval Level
    description: Everything About Approval Level
    externalDocs:
      description: Find out more
      url: 'http://kefinance.clintonhealthaccess.org/api/approval_level/docs'
schemes:
  - http
  - https
paths:











  /approval_levels:
    get:
      summary: Approval Levels List
      description: |
        The approval_level endpoint returns multiple approval_level requested given the parameters injected. 
      parameters:
        - name: approval_level_id
          in: query
          description: approval_level id 
          required: false
          type: number
          format: integer
      tags:
        - Approval Level
      responses:
        200:
          description: An array of approval_level returned
          schema:
            type: array
            items:
              $ref: '#/definitions/approval_level'
        404:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []







  /approval_level:    
    post:
      tags:
        - Approval Level
      summary: Add a new approval_level
      description: new approval_level  
      operationId: add_approval_level
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: approval_level object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/approval_level'
      responses:
        '200':
          description: Successfully added a new approval_level for approval 
        '405':
          description: Invalid input,adding a new approval_level was unsuccessful
      security:
        - api_key: []
            
            
            

            
    put:
      tags:
        - Approval Level
      summary: Update an existing approval_level
      description: ''
      operationId: update_approval_level
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: approval_level object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/approval_level'
      responses:
        200:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Success'
        '400':
          description: Invalid ID supplied
        '404':
          description: approval_level not found
        '405':
          description: Validation exception
      security:
        - api_key: []
        
        
        
        
        
        
  '/approval_level/{approval_level_id}':
    get:
      tags:
        - Approval Level
      summary: Find approval_level by ID
      description: Returns a single approval_level
      operationId: get_approval_level_by_id
      produces:
        - application/json
        - application/xml
      parameters:
        - name: approval_level_id
          in: path
          description: ID of approval_level to return object
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/approval_level'
        '400':
          description: Invalid ID supplied
        '404':
          description: approval_level not found
      security:
        - api_key: []
        
        
     
            
            
            
    delete:
      tags:
        - Approval Level
      summary: Deletes an approval_level
      description: ''
      operationId: delete_approval_level
      produces:
        - application/json
        - application/xml
      parameters:
        - name: api_key
          in: header
          required: true
          type: string
        - name: approval_level_id
          in: path
          description: approval_level id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: approval_level not found
      security:
        - api_key: []




































          
          
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
     
     
     
definitions:


      
      
  approval_level:
    type: object
    required:
      - id
      - created_at
    properties:
      id:
        type: integer
        format: int64
        example: 1
      num:
        type: number
        format: int64
        example: 20000
      str:
        type: string
        example: 'PayPal.pdf'
      date:
        type: string
        format: date-time
        example: '2010-02-11'
      created_at:
        type: string
        format: date-time
        example: '2010-02-11'
      updated_at:
        type: string
        format: date-time
        example: '2010-02-11'
    xml:
      name: approval_level
    
  
    
  
  
  
  
  Error:
    type: object
    properties:
      error:
        type: string
        example: object not found


  
  Success:
    type: object
    properties:
      msg:
        type: string
        example: object not found

      
      
      
      
