swagger: '2.0'
info:
  description: Finance management sysytem
  version: 1.0.0
  title: Grants Information Management System
  termsOfService: 'http://kefinance.clintonhealthaccess.org/terms/'
  contact:
    email: mwangikevinn@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8000'
basePath: /api
tags:
  - name: Grant Account Restriction
    description: Everything About Grant Account Restriction
    externalDocs:
      description: Find out more
      url: 'http://kefinance.clintonhealthaccess.org/api/grant_account_restriction/docs'
schemes:
  - http
  - https
paths:











  /grant_account_restrictions:
    get:
      summary: Grant Account Restrictions List
      description: |
        The grant_account_restriction endpoint returns multiple grant_account_restriction requested given the parameters injected. 
      parameters:
        - name: grant_account_restriction_id
          in: query
          description: grant_account_restriction id 
          required: false
          type: number
          format: integer
      tags:
        - Grant Account Restriction
      responses:
        200:
          description: An array of grant_account_restriction returned
          schema:
            type: array
            items:
              $ref: '#/definitions/grant_account_restriction'
        404:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []







  /grant_account_restriction:    
    post:
      tags:
        - Grant Account Restriction
      summary: Add a new grant_account_restriction
      description: new grant_account_restriction  
      operationId: add_grant_account_restriction
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: grant_account_restriction object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/grant_account_restriction'
      responses:
        '200':
          description: Successfully added a new grant_account_restriction for approval 
        '405':
          description: Invalid input,adding a new grant_account_restriction was unsuccessful
      security:
        - api_key: []
            
            
            

            
    put:
      tags:
        - Grant Account Restriction
      summary: Update an existing grant_account_restriction
      description: ''
      operationId: update_grant_account_restriction
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: grant_account_restriction object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/grant_account_restriction'
      responses:
        200:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Success'
        '400':
          description: Invalid ID supplied
        '404':
          description: grant_account_restriction not found
        '405':
          description: Validation exception
      security:
        - api_key: []
        
        
        
        
        
        
  '/grant_account_restriction/{grant_account_restriction_id}':
    get:
      tags:
        - Grant Account Restriction
      summary: Find grant_account_restriction by ID
      description: Returns a single grant_account_restriction
      operationId: get_grant_account_restriction_by_id
      produces:
        - application/json
        - application/xml
      parameters:
        - name: grant_account_restriction_id
          in: path
          description: ID of grant_account_restriction to return object
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/grant_account_restriction'
        '400':
          description: Invalid ID supplied
        '404':
          description: grant_account_restriction not found
      security:
        - api_key: []
        
        
     
            
            
            
    delete:
      tags:
        - Grant Account Restriction
      summary: Deletes an grant_account_restriction
      description: ''
      operationId: delete_grant_account_restriction
      produces:
        - application/json
        - application/xml
      parameters:
        - name: api_key
          in: header
          required: true
          type: string
        - name: grant_account_restriction_id
          in: path
          description: grant_account_restriction id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: grant_account_restriction not found
      security:
        - api_key: []




































          
          
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
     
     
     
definitions:


      
      
  grant_account_restriction:
    type: object
    required:
      - id
      - created_at
    properties:
      id:
        type: integer
        format: int64
        example: 1
      num:
        type: number
        format: int64
        example: 20000
      str:
        type: string
        example: 'PayPal.pdf'
      date:
        type: string
        format: date-time
        example: '2010-02-11'
      created_at:
        type: string
        format: date-time
        example: '2010-02-11'
      updated_at:
        type: string
        format: date-time
        example: '2010-02-11'
    xml:
      name: grant_account_restriction
    
  
    
  
  
  
  
  Error:
    type: object
    properties:
      error:
        type: string
        example: object not found


  
  Success:
    type: object
    properties:
      msg:
        type: string
        example: object not found

      
      
      
      
