swagger: '2.0'
info:
  description: Finance management sysytem
  version: 1.0.0
  title: Grants Information Management System
  termsOfService: 'https://kefinance.clintonhealthaccess.org/terms/'
  contact:
    email: mwangikevinn@gmail.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8000'
basePath: /api
tags:
  - name: Program
    description: Everything About Program
    externalDocs:
      description: Find out more
      url: 'https://kefinance.clintonhealthaccess.org/api/program/docs'
schemes:
  - http
  - https
paths:











  /programs:
    get:
      summary: programs List
      description: |
        The program endpoint returns multiple program requested given the parameters injected. 
      parameters:
        - name: program_id
          in: query
          description: program id 
          required: false
          type: number
          format: integer
      tags:
        - Program
      responses:
        200:
          description: An array of program returned
          schema:
            type: array
            items:
              $ref: '#/definitions/program'
        404:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []







  /program:    
    post:
      tags:
        - Program
      summary: Add a new program
      description: new program  
      operationId: add_program
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: program object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/program'
      responses:
        '200':
          description: Successfully added a new program for approval 
        '405':
          description: Invalid input,adding a new program was unsuccessful
      security:
        - api_key: []
            
            
            

            
    put:
      tags:
        - Program
      summary: Update an existing program
      description: ''
      operationId: update_program
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: program object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/program'
      responses:
        200:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Success'
        '400':
          description: Invalid ID supplied
        '404':
          description: program not found
        '405':
          description: Validation exception
      security:
        - api_key: []
        
        
        
        
        
        
  '/program/{program_id}':
    get:
      tags:
        - Program
      summary: Find program by ID
      description: Returns a single program
      operationId: get_program_by_id
      produces:
        - application/json
        - application/xml
      parameters:
        - name: program_id
          in: path
          description: ID of program to return object
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/program'
        '400':
          description: Invalid ID supplied
        '404':
          description: program not found
      security:
        - api_key: []
        
        
        
        
        
        
  '/program/{program_id}/managers':
    patch:
      tags:
        - Program
      summary: Update Program Managers by ID
      description: Update Program Managers
      operationId: update_managers
      produces:
        - application/json
        - application/xml
      parameters:
        - name: program_id
          in: path
          description: ID of program to return object
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/program'
        '400':
          description: Invalid ID supplied
        '404':
          description: program not found
      security:
        - api_key: []
        
        
     
            
            
            
    delete:
      tags:
        - Program
      summary: Deletes an program
      description: ''
      operationId: delete_program
      produces:
        - application/json
        - application/xml
      parameters:
        - name: api_key
          in: header
          required: true
          type: string
        - name: program_id
          in: path
          description: program id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: program not found
      security:
        - api_key: []




































          
          
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
     
     
     
definitions:


      
      
  program:
    type: object
    required:
      - id
      - created_at
    properties:
      id:
        type: integer
        format: int64
        example: 1
      num:
        type: number
        format: int64
        example: 20000
      str:
        type: string
        example: 'PayPal.pdf'
      date:
        type: string
        format: date-time
        example: '2010-02-11'
      created_at:
        type: string
        format: date-time
        example: '2010-02-11'
      updated_at:
        type: string
        format: date-time
        example: '2010-02-11'
    xml:
      name: program
    
  
    
  
  
  
  
  Error:
    type: object
    properties:
      error:
        type: string
        example: object not found


  
  Success:
    type: object
    properties:
      msg:
        type: string
        example: object not found

      
      
      
      
