swagger: '2.0'
info:
  description: Finance management sysytem
  version: 1.0.0
  title: Grants Information Management System
  termsOfService: 'http://kefinance.clintonhealthaccess.org/terms/'
  contact:
    email: mwangikevinn@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8000'
basePath: /api
tags:
  - name: Approval
    description: Everything About Approval
    externalDocs:
      description: Find out more
      url: 'http://kefinance.clintonhealthaccess.org/api/approval/docs'
schemes:
  - http
  - https
paths:











  /approvals:
    get:
      summary: approvals List
      description: |
        The approval endpoint returns multiple approval requested given the parameters injected. 
      parameters:
        - name: approval_id
          in: query
          description: approval id 
          required: false
          type: number
          format: integer
      tags:
        - Approval
      responses:
        200:
          description: An array of approval returned
          schema:
            type: array
            items:
              $ref: '#/definitions/approval'
        404:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []







  /approval:    
    post:
      tags:
        - Approval
      summary: Add a new approval
      description: new approval  
      operationId: add_approval
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: approval object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/approval'
      responses:
        '200':
          description: Successfully added a new approval for approval 
        '405':
          description: Invalid input,adding a new approval was unsuccessful
      security:
        - api_key: []
            
            
            

            
    put:
      tags:
        - Approval
      summary: Update an existing approval
      description: ''
      operationId: update_approval
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: approval object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/approval'
      responses:
        200:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Success'
        '400':
          description: Invalid ID supplied
        '404':
          description: approval not found
        '405':
          description: Validation exception
      security:
        - api_key: []
        
        
        
        
        
        
  '/approval/{approval_id}':
    get:
      tags:
        - Approval
      summary: Find approval by ID
      description: Returns a single approval
      operationId: get_approval_by_id
      produces:
        - application/json
        - application/xml
      parameters:
        - name: approval_id
          in: path
          description: ID of approval to return object
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/approval'
        '400':
          description: Invalid ID supplied
        '404':
          description: approval not found
      security:
        - api_key: []
        
        
     
            
            
            
    delete:
      tags:
        - Approval
      summary: Deletes an approval
      description: ''
      operationId: delete_approval
      produces:
        - application/json
        - application/xml
      parameters:
        - name: api_key
          in: header
          required: true
          type: string
        - name: approval_id
          in: path
          description: approval id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: approval not found
      security:
        - api_key: []




































          
          
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
     
     
     
definitions:


      
      
  approval:
    type: object
    required:
      - id
      - created_at
    properties:
      id:
        type: integer
        format: int64
        example: 1
      num:
        type: number
        format: int64
        example: 20000
      str:
        type: string
        example: 'PayPal.pdf'
      date:
        type: string
        format: date-time
        example: '2010-02-11'
      created_at:
        type: string
        format: date-time
        example: '2010-02-11'
      updated_at:
        type: string
        format: date-time
        example: '2010-02-11'
    xml:
      name: approval
    
  
    
  
  
  
  
  Error:
    type: object
    properties:
      error:
        type: string
        example: object not found


  
  Success:
    type: object
    properties:
      msg:
        type: string
        example: object not found

      
      
      
      
