swagger: '2.0'
info:
  description: Finance management sysytem
  version: 1.0.0
  title: Grants Information Management System
  termsOfService: 'https://kefinance.clintonhealthaccess.org/terms/'
  contact:
    email: mwangikevinn@gmail.com
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8000'
basePath: /api
tags:
  - name: City
    description: Everything About City
    externalDocs:
      description: Find out more
      url: 'https://kefinance.clintonhealthaccess.org/api/city/docs'
schemes:
  - http
  - https
paths:











  /cities:
    get:
      summary: Cities List
      description: |
        The city endpoint returns multiple city requested given the parameters injected. 
      parameters:
        - name: city_id
          in: query
          description: city id 
          required: false
          type: number
          format: integer
      tags:
        - City
      responses:
        200:
          description: An array of city returned
          schema:
            type: array
            items:
              $ref: '#/definitions/city'
        404:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []







  /city:    
    post:
      tags:
        - City
      summary: Add a new city
      description: new city  
      operationId: add_city
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: city object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/city'
      responses:
        '200':
          description: Successfully added a new city for approval 
        '405':
          description: Invalid input,adding a new city was unsuccessful
      security:
        - api_key: []
            
            
            

            
    put:
      tags:
        - City
      summary: Update an existing city
      description: ''
      operationId: update_city
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: city object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/city'
      responses:
        200:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Success'
        '400':
          description: Invalid ID supplied
        '404':
          description: city not found
        '405':
          description: Validation exception
      security:
        - api_key: []
        
        
        
        
        
        
  '/city/{city_id}':
    get:
      tags:
        - City
      summary: Find city by ID
      description: Returns a single city
      operationId: get_city_by_id
      produces:
        - application/json
        - application/xml
      parameters:
        - name: city_id
          in: path
          description: ID of city to return object
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/city'
        '400':
          description: Invalid ID supplied
        '404':
          description: city not found
      security:
        - api_key: []
        
        
     
            
            
            
    delete:
      tags:
        - City
      summary: Deletes an city
      description: ''
      operationId: delete_city
      produces:
        - application/json
        - application/xml
      parameters:
        - name: api_key
          in: header
          required: true
          type: string
        - name: city_id
          in: path
          description: city id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: city not found
      security:
        - api_key: []




































          
          
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
     
     
     
definitions:


      
      
  city:
    type: object
    required:
      - id
      - created_at
    properties:
      id:
        type: integer
        format: int64
        example: 1
      num:
        type: number
        format: int64
        example: 20000
      str:
        type: string
        example: 'PayPal.pdf'
      date:
        type: string
        format: date-time
        example: '2010-02-11'
      created_at:
        type: string
        format: date-time
        example: '2010-02-11'
      updated_at:
        type: string
        format: date-time
        example: '2010-02-11'
    xml:
      name: city
    
  
    
  
  
  
  
  Error:
    type: object
    properties:
      error:
        type: string
        example: object not found


  
  Success:
    type: object
    properties:
      msg:
        type: string
        example: object not found

      
      
      
      
