swagger: '2.0'
info:
  description: Finance management sysytem
  version: 1.0.0
  title: Grants Information Management System
  termsOfService: 'http://kefinance.clintonhealthaccess.org/terms/'
  contact:
    email: mwangikevinn@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8000'
basePath: /api
tags:
  - name: Country
    description: Everything About Country
    externalDocs:
      description: Find out more
      url: 'http://kefinance.clintonhealthaccess.org/api/country/docs'
schemes:
  - http
  - https
paths:











  /countries:
    get:
      summary: Countries List
      description: |
        The country endpoint returns multiple country requested given the parameters injected. 
      parameters:
        - name: country_id
          in: query
          description: country id 
          required: false
          type: number
          format: integer
      tags:
        - Country
      responses:
        200:
          description: An array of country returned
          schema:
            type: array
            items:
              $ref: '#/definitions/country'
        404:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []







  /country:    
    post:
      tags:
        - Country
      summary: Add a new country
      description: new country  
      operationId: add_country
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: country object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/country'
      responses:
        '200':
          description: Successfully added a new country for approval 
        '405':
          description: Invalid input,adding a new country was unsuccessful
      security:
        - api_key: []
            
            
            

            
    put:
      tags:
        - Country
      summary: Update an existing country
      description: ''
      operationId: update_country
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: country object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/country'
      responses:
        200:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Success'
        '400':
          description: Invalid ID supplied
        '404':
          description: country not found
        '405':
          description: Validation exception
      security:
        - api_key: []
        
        
        
        
        
        
  '/country/{country_id}':
    get:
      tags:
        - Country
      summary: Find country by ID
      description: Returns a single country
      operationId: get_country_by_id
      produces:
        - application/json
        - application/xml
      parameters:
        - name: country_id
          in: path
          description: ID of country to return object
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/country'
        '400':
          description: Invalid ID supplied
        '404':
          description: country not found
      security:
        - api_key: []
        
        
     
            
            
            
    delete:
      tags:
        - Country
      summary: Deletes an country
      description: ''
      operationId: delete_country
      produces:
        - application/json
        - application/xml
      parameters:
        - name: api_key
          in: header
          required: true
          type: string
        - name: country_id
          in: path
          description: country id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: country not found
      security:
        - api_key: []




































          
          
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
     
     
     
definitions:


      
      
  country:
    type: object
    required:
      - id
      - created_at
    properties:
      id:
        type: integer
        format: int64
        example: 1
      num:
        type: number
        format: int64
        example: 20000
      str:
        type: string
        example: 'PayPal.pdf'
      date:
        type: string
        format: date-time
        example: '2010-02-11'
      created_at:
        type: string
        format: date-time
        example: '2010-02-11'
      updated_at:
        type: string
        format: date-time
        example: '2010-02-11'
    xml:
      name: country
    
  
    
  
  
  
  
  Error:
    type: object
    properties:
      error:
        type: string
        example: object not found


  
  Success:
    type: object
    properties:
      msg:
        type: string
        example: object not found

      
      
      
      
