swagger: '2.0'
info:
  description: Finance management sysytem
  version: 1.0.0
  title: Grants Information Management System
  termsOfService: 'http://kefinance.clintonhealthaccess.org/terms/'
  contact:
    email: mwangikevinn@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:8000'
basePath: /api
tags:
  - name: Staff
    description: Everything About Staff
    externalDocs:
      description: Find out more
      url: 'http://kefinance.clintonhealthaccess.org/api/staff/docs'
schemes:
  - http
  - https
paths:











  /staffs:
    get:
      summary: staffs List
      description: |
        The staff endpoint returns multiple staff requested given the parameters injected. 
      parameters:
        - name: staff_id
          in: query
          description: staff id 
          required: false
          type: number
          format: integer
      tags:
        - Staff
      responses:
        200:
          description: An array of staff returned
          schema:
            type: array
            items:
              $ref: '#/definitions/staff'
        404:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      security:
        - api_key: []







  /staff:    
    post:
      tags:
        - Staff
      summary: Add a new staff
      description: new staff  
      operationId: add_staff
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: staff object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/staff'
      responses:
        '200':
          description: Successfully added a new staff for approval 
        '405':
          description: Invalid input,adding a new staff was unsuccessful
      security:
        - api_key: []
            
            
            

            
    put:
      tags:
        - Staff
      summary: Update an existing staff
      description: ''
      operationId: update_staff
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: staff object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/staff'
      responses:
        200:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Success'
        '400':
          description: Invalid ID supplied
        '404':
          description: staff not found
        '405':
          description: Validation exception
      security:
        - api_key: []
        
        
        
        
        
        
  '/staff/{staff_id}':
    get:
      tags:
        - Staff
      summary: Find staff by ID
      description: Returns a single staff
      operationId: get_staff_by_id
      produces:
        - application/json
        - application/xml
      parameters:
        - name: staff_id
          in: path
          description: ID of staff to return object
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/staff'
        '400':
          description: Invalid ID supplied
        '404':
          description: staff not found
      security:
        - api_key: []
        
        
     
            
            
            
    delete:
      tags:
        - Staff
      summary: Deletes an staff
      description: ''
      operationId: delete_staff
      produces:
        - application/json
        - application/xml
      parameters:
        - name: api_key
          in: header
          required: true
          type: string
        - name: staff_id
          in: path
          description: staff id to delete
          required: true
          type: integer
          format: int64
      responses:
        '400':
          description: Invalid ID supplied
        '404':
          description: staff not found
      security:
        - api_key: []




































          
          
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
     
     
     
definitions:


      
      
  staff:
    type: object
    required:
      - id
      - created_at
    properties:
      id:
        type: integer
        format: int64
        example: 1
      num:
        type: number
        format: int64
        example: 20000
      str:
        type: string
        example: 'PayPal.pdf'
      date:
        type: string
        format: date-time
        example: '2010-02-11'
      created_at:
        type: string
        format: date-time
        example: '2010-02-11'
      updated_at:
        type: string
        format: date-time
        example: '2010-02-11'
    xml:
      name: staff
    
  
    
  
  
  
  
  Error:
    type: object
    properties:
      error:
        type: string
        example: object not found


  
  Success:
    type: object
    properties:
      msg:
        type: string
        example: object not found

      
      
      
      
