<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class AdvanceAllocationApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation addAdvanceAllocation
     *
     * Add a new advance_allocation.
     *
     *
     * @return Http response
     */
    public function addAdvanceAllocation()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addAdvanceAllocation');
        }
        $body = $input['body'];


        return response('How about implementing addAdvanceAllocation as a POST method ?');
    }
    /**
     * Operation updateAdvanceAllocation
     *
     * Update an existing advance_allocation.
     *
     *
     * @return Http response
     */
    public function updateAdvanceAllocation()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateAdvanceAllocation');
        }
        $body = $input['body'];


        return response('How about implementing updateAdvanceAllocation as a PUT method ?');
    }
    /**
     * Operation deleteAdvanceAllocation
     *
     * Deletes an advance_allocation.
     *
     * @param int $advance_allocation_id advance_allocation id to delete (required)
     *
     * @return Http response
     */
    public function deleteAdvanceAllocation($advance_allocation_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteAdvanceAllocation as a DELETE method ?');
    }
    /**
     * Operation getAdvanceAllocationById
     *
     * Find advance_allocation by ID.
     *
     * @param int $advance_allocation_id ID of advance_allocation to return object (required)
     *
     * @return Http response
     */
    public function getAdvanceAllocationById($advance_allocation_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getAdvanceAllocationById as a GET method ?');
    }
    /**
     * Operation advanceAllocationsGet
     *
     * advance_allocations List.
     *
     *
     * @return Http response
     */
    public function advanceAllocationsGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $advance_allocation_id = $input['advance_allocation_id'];


        return response('How about implementing advanceAllocationsGet as a GET method ?');
    }
}
