<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class BankTransactionApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation addBankTransaction
     *
     * Add a new bank_transaction.
     *
     *
     * @return Http response
     */
    public function addBankTransaction()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addBankTransaction');
        }
        $body = $input['body'];


        return response('How about implementing addBankTransaction as a POST method ?');
    }
    /**
     * Operation updateBankTransaction
     *
     * Update an existing bank_transaction.
     *
     *
     * @return Http response
     */
    public function updateBankTransaction()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateBankTransaction');
        }
        $body = $input['body'];


        return response('How about implementing updateBankTransaction as a PUT method ?');
    }
    /**
     * Operation deleteBankTransaction
     *
     * Deletes an bank_transaction.
     *
     * @param int $bank_transaction_id bank_transaction id to delete (required)
     *
     * @return Http response
     */
    public function deleteBankTransaction($bank_transaction_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteBankTransaction as a DELETE method ?');
    }
    /**
     * Operation getBankTransactionById
     *
     * Find bank_transaction by ID.
     *
     * @param int $bank_transaction_id ID of bank_transaction to return object (required)
     *
     * @return Http response
     */
    public function getBankTransactionById($bank_transaction_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getBankTransactionById as a GET method ?');
    }
    /**
     * Operation bankTransactionsGet
     *
     * bank_transactions List.
     *
     *
     * @return Http response
     */
    public function bankTransactionsGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $bank_transaction_id = $input['bank_transaction_id'];


        return response('How about implementing bankTransactionsGet as a GET method ?');
    }
}
