<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use App\Models\AllocationModels\Allocation;

class ClaimAllocationApi extends Controller
{
    /**
     * Operation getClaimAllocationById
     *
     * Find claim_allocation by ID.
     *
     * @param int $claim_allocation_id ID of claim_allocation to return object (required)
     *
     * @return Http response
     */
    public function getClaimAllocationById($claim_allocation_id)
    {
        $response = [];

        try{
            $response   = Allocation::with( 
                                        'allocatable',
                                        'allocated_by',
                                        'project',
                                        'account'
                                    )->findOrFail($claim_allocation_id);


            $response['claim']  =   $response['allocatable'];
            return response()->json($response, 200,array(),JSON_PRETTY_PRINT);

        }catch(Exception $e){
            $response =  ["error"=>"Claim Allocation could not be found"];
            return response()->json($response, 404,array(),JSON_PRETTY_PRINT);
        }
    }
}
