<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;
use App\Models\LookupModels\Currency;

class CurrencyApi extends Controller
{
    /**
     * Operation currenciesGet
     *
     * currencies List.
     *
     *
     * @return Http response
     */
    public function currenciesGet()
    {
         $response = Currency::all();
          return response()->json($response, 200,array(),JSON_PRETTY_PRINT);
    }
}
