<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use JWTAuth;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\DB;
use App\Models\InvoicesModels\InvoiceStatus;
use App\Models\InvoicesModels\Invoice;

class InvoiceStatusApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }





























    

    /**
     * Operation addInvoiceStatus
     *
     * Add a new invoice_status.
     *
     *
     * @return Http response
     */
    public function addInvoiceStatus()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addInvoiceStatus');
        }
        $body = $input['body'];


        return response('How about implementing addInvoiceStatus as a POST method ?');
    }





























    
    /**
     * Operation updateInvoiceStatus
     *
     * Update an existing invoice_status.
     *
     *
     * @return Http response
     */
    public function updateInvoiceStatus()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateInvoiceStatus');
        }
        $body = $input['body'];


        return response('How about implementing updateInvoiceStatus as a PUT method ?');
    }





























    
    /**
     * Operation deleteInvoiceStatus
     *
     * Deletes an invoice_status.
     *
     * @param int $invoice_status_id invoice_status id to delete (required)
     *
     * @return Http response
     */
    public function deleteInvoiceStatus($invoice_status_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteInvoiceStatus as a DELETE method ?');
    }





























    
    /**
     * Operation getInvoiceStatusById
     *
     * Find invoice_status by ID.
     *
     * @param int $invoice_status_id ID of invoice_status to return object (required)
     *
     * @return Http response
     */
    public function getInvoiceStatusById($invoice_status_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getInvoiceStatusById as a GET method ?');
    }





























    
    /**
     * Operation getInvoiceStatuses
     *
     * invoice_statuses List.
     *
     *
     * @return Http response
     */
    public function getInvoiceStatuses()
    {
        
        $input = Request::all();
        $response;
        $qb = DB::table('invoice_statuses');
        $qb->whereNull('deleted_at');

        $user = JWTAuth::parseToken()->authenticate();


        if(array_key_exists('allowed_only', $input)){

            $qb = $this->get_my_allowed_statuses($qb);

        }else{

            $qb->orderBy('invoice_status', 'DESC');
        }


        $response = $qb->get();
        $response = json_decode(json_encode($response),true);

      


        //count lpos on each status
        foreach ($response as $key => $value) {


            $response[$key]['invoices_count'] = Invoice::where('raised_by_id',$this->current_user()->id)
                                            ->where('status_id', $value['id'] )
                                            ->count();


        }

        //add -1 and -2 statuses

        if(array_key_exists('allowed_only', $input)){

            //-1
            $response[]=array(
                    "id"=> -1,
                    "invoice_status"=> "My Invoices",
                    "order_priority"=> 998,
                    "display_color"=> "#37A9E17A",
                    "invoices_count"=> Invoice::where('raised_by_id',$this->current_user()->id)->count()
                  );




            if ($user->hasRole('program-manager')){
                $response[]=array(
                        "id"=> -3,
                        "invoice_status"=> "My PM-Assigned Invoices",
                        "order_priority"=> 999,
                        "display_color"=> "#49149c7a",
                        "invoices_count"=> Invoice::where('project_manager_id',$this->current_user()->id)->count()
                      );
            }
            
            if ($user->can('READ_INVOICE_-2')){
                //-2
                $response[]=array(
                        "id"=> -2,
                        "invoice_status"=> "All Invoices",
                        "order_priority"=> 1000,
                        "display_color"=> "#092D50",
                        "invoices_count"=> Invoice::count()
                      );
            }



        }

        return response()->json($response, 200,array(),JSON_PRETTY_PRINT);

    }

    

    private function get_my_allowed_statuses($qb){


        $qb->orderBy('order_priority', 'ASC');

        return $qb;
    }
}
