<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class InvoiceApprovalApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }





























    

    /**
     * Operation addInvoiceApproval
     *
     * Add a new invoice_approval.
     *
     *
     * @return Http response
     */
    public function addInvoiceApproval()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addInvoiceApproval');
        }
        $body = $input['body'];


        return response('How about implementing addInvoiceApproval as a POST method ?');
    }





























    
    /**
     * Operation updateInvoiceApproval
     *
     * Update an existing invoice_approval.
     *
     *
     * @return Http response
     */
    public function updateInvoiceApproval()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateInvoiceApproval');
        }
        $body = $input['body'];


        return response('How about implementing updateInvoiceApproval as a PUT method ?');
    }





























    
    /**
     * Operation deleteInvoiceApproval
     *
     * Deletes an invoice_approval.
     *
     * @param int $invoice_approval_id invoice_approval id to delete (required)
     *
     * @return Http response
     */
    public function deleteInvoiceApproval($invoice_approval_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteInvoiceApproval as a DELETE method ?');
    }





























    
    /**
     * Operation getInvoiceApprovalById
     *
     * Find invoice_approval by ID.
     *
     * @param int $invoice_approval_id ID of invoice_approval to return object (required)
     *
     * @return Http response
     */
    public function getInvoiceApprovalById($invoice_approval_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getInvoiceApprovalById as a GET method ?');
    }





























    
    /**
     * Operation getInvoiceApprovals
     *
     * invoice_approvals List.
     *
     *
     * @return Http response
     */
    public function getInvoiceApprovals()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $invoice_approval_id = $input['invoice_approval_id'];


        return response('How about implementing getInvoiceApprovals as a GET method ?');
    }
}
