<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class LPOQuotationApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation addLpoQuotation
     *
     * Add a new lpo quotation.
     *
     *
     * @return Http response
     */
    public function addLpoQuotation()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addLpoQuotation');
        }
        $body = $input['body'];


        return response('How about implementing addLpoQuotation as a POST method ?');
    }
    /**
     * Operation updateLpoQuotation
     *
     * Update an existing LPO Quotation.
     *
     *
     * @return Http response
     */
    public function updateLpoQuotation()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateLpoQuotation');
        }
        $body = $input['body'];


        return response('How about implementing updateLpoQuotation as a PUT method ?');
    }
    /**
     * Operation deleteLpoQuotation
     *
     * Deletes an lpo_quotation.
     *
     * @param int $lpo_quotation_id lpo quotation id to delete (required)
     *
     * @return Http response
     */
    public function deleteLpoQuotation($lpo_quotation_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteLpoQuotation as a DELETE method ?');
    }
    /**
     * Operation getLpoQuotationById
     *
     * Find lpo quotation by ID.
     *
     * @param int $lpo_quotation_id ID of lpo quotation to return object (required)
     *
     * @return Http response
     */
    public function getLpoQuotationById($lpo_quotation_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getLpoQuotationById as a GET method ?');
    }
    /**
     * Operation lpoQuotationsGet
     *
     * lpo quotations List.
     *
     *
     * @return Http response
     */
    public function lpoQuotationsGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $lpo_id = $input['lpo_id'];


        return response('How about implementing lpoQuotationsGet as a GET method ?');
    }
}
