<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\DB;
use App\Models\MobilePaymentModels\MobilePaymentStatus;
use App\Models\MobilePaymentModels\MobilePayment;
use JWTAuth;

class MobilePaymentStatusApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }



























    

    /**
     * Operation addMobilePaymentStatus
     *
     * Add a new mobile_payment_status.
     *
     *
     * @return Http response
     */
    public function addMobilePaymentStatus()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addMobilePaymentStatus');
        }
        $body = $input['body'];


        return response('How about implementing addMobilePaymentStatus as a POST method ?');
    }



























    
    /**
     * Operation updateMobilePaymentStatus
     *
     * Update an existing mobile_payment_status.
     *
     *
     * @return Http response
     */
    public function updateMobilePaymentStatus()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateMobilePaymentStatus');
        }
        $body = $input['body'];


        return response('How about implementing updateMobilePaymentStatus as a PUT method ?');
    }



























    
    /**
     * Operation deleteMobilePaymentStatus
     *
     * Deletes an mobile_payment_status.
     *
     * @param int $mobile_payment_status_id mobile_payment_status id to delete (required)
     *
     * @return Http response
     */
    public function deleteMobilePaymentStatus($mobile_payment_status_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteMobilePaymentStatus as a DELETE method ?');
    }



























    
    /**
     * Operation getMobilePaymentStatusById
     *
     * Find mobile_payment_status by ID.
     *
     * @param int $mobile_payment_status_id ID of mobile_payment_status to return object (required)
     *
     * @return Http response
     */
    public function getMobilePaymentStatusById($mobile_payment_status_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getMobilePaymentStatusById as a GET method ?');
    }




































    /**
     * Operation mobilePaymentStatusesGet
     *
     * mobile_payment_statuses List.
     *
     *
     * @return Http response
     */
    public function mobilePaymentStatusesGet()
    {
        
        $input = Request::all();
        $response;
        $qb = DB::table('mobile_payment_statuses');
        $qb->whereNull('deleted_at');

        $user = JWTAuth::parseToken()->authenticate();

        if(array_key_exists('allowed_only', $input)){

            $qb = $this->get_my_allowed_statuses($qb);

        }else{

            $qb->orderBy('mobile_payment_status', 'DESC');
        }


        $response = $qb->get();
        $response = json_decode(json_encode($response),true);

      


        //count lpos on each status
        foreach ($response as $key => $value) {


            $response[$key]['mobile_payments_count'] = MobilePayment::where('requested_by_id',$this->current_user()->id)
                                            ->where('status_id', $value['id'] )
                                            ->count();


        }

        //add -1 and -2 statuses

        if(array_key_exists('allowed_only', $input)){

            //-1
            $response[]=array(
                    "id"=> -1,
                    "mobile_payment_status"=> "My Mobile Payments",
                    "order_priority"=> 999,
                    "display_color"=> "#37A9E17A",
                    "mobile_payments_count"=> MobilePayment::where('requested_by_id',$this->current_user()->id)->count()
                  );



            if ($user->can('READ_MOBILEPAYMENT_-2')){
                //-1
                $response[]=array(
                        "id"=> -2,
                        "mobile_payment_status"=> "All Mobile Payments",
                        "order_priority"=> 1000,
                        "display_color"=> "#092D50",
                        "mobile_payments_count"=> MobilePayment::count()
                      );
            }

        }

        return response()->json($response, 200,array(),JSON_PRETTY_PRINT);

    }


    private function get_my_allowed_statuses($qb){


        $qb->orderBy('order_priority', 'ASC');

        return $qb;
    }
}
