<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class PaymentTypeApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }


























    

    /**
     * Operation addPaymentType
     *
     * Add a new payment_type.
     *
     *
     * @return Http response
     */
    public function addPaymentType()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addPaymentType');
        }
        $body = $input['body'];


        return response('How about implementing addPaymentType as a POST method ?');
    }


























    
    /**
     * Operation updatePaymentType
     *
     * Update an existing payment_type.
     *
     *
     * @return Http response
     */
    public function updatePaymentType()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updatePaymentType');
        }
        $body = $input['body'];


        return response('How about implementing updatePaymentType as a PUT method ?');
    }


























    
    /**
     * Operation deletePaymentType
     *
     * Deletes an payment_type.
     *
     * @param int $payment_type_id payment_type id to delete (required)
     *
     * @return Http response
     */
    public function deletePaymentType($payment_type_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deletePaymentType as a DELETE method ?');
    }


























    
    /**
     * Operation getPaymentTypeById
     *
     * Find payment_type by ID.
     *
     * @param int $payment_type_id ID of payment_type to return object (required)
     *
     * @return Http response
     */
    public function getPaymentTypeById($payment_type_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getPaymentTypeById as a GET method ?');
    }


























    
    /**
     * Operation getPaymentTypes
     *
     * payment_types List.
     *
     *
     * @return Http response
     */
    public function getPaymentTypes()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $payment_type_id = $input['payment_type_id'];


        return response('How about implementing getPaymentTypes as a GET method ?');
    }
}
