<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class PaymentApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }






















    

    /**
     * Operation addPayment
     *
     * Add a new payment.
     *
     *
     * @return Http response
     */
    public function addPayment()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addPayment');
        }
        $body = $input['body'];


        return response('How about implementing addPayment as a POST method ?');
    }






















    
    /**
     * Operation updatePayment
     *
     * Update an existing payment.
     *
     *
     * @return Http response
     */
    public function updatePayment()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updatePayment');
        }
        $body = $input['body'];


        return response('How about implementing updatePayment as a PUT method ?');
    }






















    
    /**
     * Operation getPaymentById
     *
     * Find payment by ID.
     *
     * @param int $payment_id ID of payment to return object (required)
     *
     * @return Http response
     */
    public function getPaymentById($payment_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getPaymentById as a GET method ?');
    }






















    
    /**
     * Operation deletePayment
     *
     * Deletes an payment.
     *
     * @param int $payment_id payment id to delete (required)
     *
     * @return Http response
     */
    public function deletePayment($payment_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deletePayment as a DELETE method ?');
    }






















    
    /**
     * Operation getDocumentById
     *
     * get payment document by ID.
     *
     * @param int $payment_id ID of payment to return object (required)
     *
     * @return Http response
     */
    public function getDocumentById($payment_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getDocumentById as a GET method ?');
    }






















    
    /**
     * Operation getPayments
     *
     * payments List.
     *
     *
     * @return Http response
     */
    public function getPayments()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $payment_id = $input['payment_id'];


        return response('How about implementing getPayments as a GET method ?');
    }
}
