<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;


use JWTAuth;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\DB;

use App\Models\ProgramModels\Program;
use App\Models\ProgramModels\ProgramManager;
use App\Models\ProgramModels\ProgramStaff;


use Exception;
use App;
use Illuminate\Support\Facades\Response;
use App\Models\StaffModels\Staff;

class ProgramApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    




















    /**
     * Operation addProgram
     *
     * Add a new program.
     *
     *
     * @return Http response
     */
    public function addProgram()
    {
        $form = Request::only(
            'program_name',
            'program_desc'
            );

        $program = new Program;

            $program->program_name                   =         $form['program_name'];
            $program->program_desc                   =         $form['program_desc'];

        if($program->save()) {

            return Response()->json(array('msg' => 'Success: program added','program' => $program), 200);
        }
    }
    




















    /**
     * Operation updateProgram
     *
     * Update an existing program.
     *
     *
     * @return Http response
     */
    public function updateProgram()
    {
        $form = Request::only(
            'id',
            'program_name',
            'program_desc'
            );

        $program = Program::find($form['id']);

            $program->program_name                   =         $form['program_name'];
            $program->program_desc                   =         $form['program_desc'];

        if($program->save()) {

            return Response()->json(array('msg' => 'Success: program updated','program' => $program), 200);
        }
    }
    




















    /**
     * Operation deleteProgram
     *
     * Deletes an program.
     *
     * @param int $program_id program id to delete (required)
     *
     * @return Http response
     */
    public function deleteProgram($program_id)
    {
        $input = Request::all();


        $deleted = Program::destroy($program_id);

        if($deleted){
            return response()->json(['msg'=>"program deleted"], 200,array(),JSON_PRETTY_PRINT);
        }else{
            return response()->json(['error'=>"program not found"], 404,array(),JSON_PRETTY_PRINT);
        }
    }
    
    



















    /**

     * Operation getProgramById
     *
     * Find program by ID.
     *
     * @param int $program_id ID of program to return object (required)
     *
     * @return Http response
     */
    public function getProgramById($program_id)
    {
        $input = Request::all();

        try{

            $response   = Program::with("managers")->findOrFail($program_id);
           
            return response()->json($response, 200,array(),JSON_PRETTY_PRINT);

        }catch(Exception $e){

            $response =  ["error"=>"program could not be found"];
            return response()->json($response, 404,array(),JSON_PRETTY_PRINT);
        }
    }






















    /**
     * Operation updateManagers
     *
     * Update Program Managers by ID.
     *
     * @param int $program_id ID of program to return object (required)
     *
     * @return Http response
     */
    public function updateManagers($program_id)
    {
        $form = Request::only(
            'managers',
            );

        try{

            $program    =   Program::findOrFail($staff_id);
            $program->managers()->sync($form->managers);
            $response   =   Program::with("managers")->findOrFail($program_id);
           
            return response()->json(['msg'=>"Managers Updated", 'managers'=>$response], 200,array(),JSON_PRETTY_PRINT);

        }catch(Exception $e){

            $response =  ["error"=>"program could not be found"];
            return response()->json($response, 404,array(),JSON_PRETTY_PRINT);
        }
    }
    




















    /**
     * Operation programsGet
     *
     * programs List.
     *
     *
     * @return Http response
     */
    public function programsGet()
    {
        


        $input = Request::all();
        //query builder
        $qb = DB::table('programs');

        $qb->whereNull('programs.deleted_at');
        $current_user = JWTAuth::parseToken()->authenticate();

        $response;
        $response_dt;

        $total_records          = $qb->count();
        $records_filtered       = 0;




        //my_pm_assigned
        if(array_key_exists('my_pm_assigned', $input)&& $input['my_pm_assigned'] = "true"){


            $qb->select(DB::raw('programs.*'))
                 ->rightJoin('program_managers', 'program_managers.program_id', '=', 'programs.id')
                 ->rightJoin('staff', 'staff.id', '=', 'program_managers.program_manager_id')
                 ->where('staff.id', '=', $current_user->id)
                 ->whereNotNull('programs.id')
                 ->groupBy('programs.id')
                 ->orderBy('programs.program_name', 'asc');
        }

        //searching
        if(array_key_exists('searchval', $input)){
            $qb->where(function ($query) use ($input) {
                
                $query->orWhere('programs.id','like', '\'%' . $input['searchval']. '%\'');
                $query->orWhere('programs.program_name','like', '\'%' . $input['searchval']. '%\'');
                $query->orWhere('programs.program_desc','like', '\'%' . $input['searchval']. '%\'');

            });

            // $records_filtered       =  $qb->count(); //doesn't work

            $sql = Program::bind_presql($qb->toSql(),$qb->getBindings());
            $sql = str_replace("*"," count(*) AS count ", $sql);
            $dt = json_decode(json_encode(DB::select($sql)), true);

            $records_filtered = (int) $dt[0]['count'];
            // $records_filtered = 30;


        }


        //ordering
        if(array_key_exists('order_by', $input)&&$input['order_by']!=''){
            $order_direction     = "asc";
            $order_column_name   = $input['order_by'];
            if(array_key_exists('order_dir', $input)&&$input['order_dir']!=''){                
                $order_direction = $input['order_dir'];
            }

            $qb->orderBy($order_column_name, $order_direction);
        }else{
            //$qb->orderBy("project_code", "asc");
        }

        //limit
        if(array_key_exists('limit', $input)){


            $qb->limit($input['limit']);


        }

        //migrated
        if(array_key_exists('migrated', $input)){

            $mig = (int) $input['migrated'];

            if($mig==0){
                $qb->whereNull('migration_id');
            }else if($mig==1){
                $qb->whereNotNull('migration_id');
            }


        }



        if(array_key_exists('datatables', $input)){

            //searching
            $qb->where(function ($query) use ($input) {
                
                $query->orWhere('programs.id','like', '\'%' . $input['search']['value']. '%\'');
                $query->orWhere('programs.program_name','like', '\'%' . $input['search']['value']. '%\'');
                $query->orWhere('programs.program_desc','like', '\'%' . $input['search']['value']. '%\'');

            });




            $sql = Program::bind_presql($qb->toSql(),$qb->getBindings());
            $sql = str_replace("*"," count(*) AS count ", $sql);
            $dt = json_decode(json_encode(DB::select($sql)), true);

            $records_filtered = (int) $dt[0]['count'];


            //ordering
            $order_column_id    = (int) $input['order'][0]['column'];
            $order_column_name  = $input['columns'][$order_column_id]['order_by'];
            $order_direction    = $input['order'][0]['dir'];

            if($order_column_name!=''){

                $qb->orderBy($order_column_name, $order_direction);

            }






            //limit $ offset
            if((int)$input['start']!= 0 ){

                $response_dt    =   $qb->limit($input['length'])->offset($input['start']);

            }else{
                $qb->limit($input['length']);
            }





            $sql = Program::bind_presql($qb->toSql(),$qb->getBindings());

            // $response_dt = DB::select($qb->toSql(),$qb->getBindings());         //pseudo
            $response_dt = DB::select($sql);


            $response_dt = json_decode(json_encode($response_dt), true);

            $response_dt    = $this->append_relationships_objects($response_dt);
            $response_dt    = $this->append_relationships_nulls($response_dt);
            $response       = Program::arr_to_dt_response( 
                $response_dt, $input['draw'],
                $total_records,
                $records_filtered
                );


        }else{

            $sql            = Program::bind_presql($qb->toSql(),$qb->getBindings());
            $response       = json_decode(json_encode(DB::select($sql)), true);
            if(!array_key_exists('lean', $input)){
                $response       = $this->append_relationships_objects($response);
                $response       = $this->append_relationships_nulls($response);
            }
        }




        return response()->json($response, 200,array(),JSON_PRETTY_PRINT);


    }




















    public function append_relationships_objects($data = array()){


        foreach ($data as $key => $value) {

            $programs = Program::find($data[$key]['id']);

            $data[$key]['managers']                = $programs->managers;
            $data[$key]['staffs']                  = $programs->staffs;

        }


        return $data;


    }










    



    public function append_relationships_nulls($data = array()){


        foreach ($data as $key => $value) {


            // if($data[$key]["account"]==null){
            //     $data[$key]["account"] = array("account_name"=>"N/A");
            // }


        }

        return $data;


    }
}
