<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class SupplyCategoryItemApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation addSupplyCategoryItem
     *
     * Add a new supply_category_item.
     *
     *
     * @return Http response
     */
    public function addSupplyCategoryItem()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addSupplyCategoryItem');
        }
        $body = $input['body'];


        return response('How about implementing addSupplyCategoryItem as a POST method ?');
    }
    /**
     * Operation updateSupplyCategoryItem
     *
     * Update an existing supply_category_item.
     *
     *
     * @return Http response
     */
    public function updateSupplyCategoryItem()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateSupplyCategoryItem');
        }
        $body = $input['body'];


        return response('How about implementing updateSupplyCategoryItem as a PUT method ?');
    }
    /**
     * Operation deleteSupplyCategoryItem
     *
     * Deletes an supply_category_item.
     *
     * @param int $supply_category_item_id supply_category_item id to delete (required)
     *
     * @return Http response
     */
    public function deleteSupplyCategoryItem($supply_category_item_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteSupplyCategoryItem as a DELETE method ?');
    }
    /**
     * Operation getSupplyCategoryItemById
     *
     * Find supply_category_item by ID.
     *
     * @param int $supply_category_item_id ID of supply_category_item to return object (required)
     *
     * @return Http response
     */
    public function getSupplyCategoryItemById($supply_category_item_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getSupplyCategoryItemById as a GET method ?');
    }
    /**
     * Operation supplyCategoryItemsGet
     *
     * supply_category_items List.
     *
     *
     * @return Http response
     */
    public function supplyCategoryItemsGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $supply_category_item_id = $input['supply_category_item_id'];


        return response('How about implementing supplyCategoryItemsGet as a GET method ?');
    }
}
