<?php

/**
 * Grants Information Management System
 * Finance management sysytem
 *
 * OpenAPI spec version: 1.0.0
 * Contact: mwangikevinn@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class SupplierRateApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation addSupplierRate
     *
     * Add a new supplier_rate.
     *
     *
     * @return Http response
     */
    public function addSupplierRate()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling addSupplierRate');
        }
        $body = $input['body'];


        return response('How about implementing addSupplierRate as a POST method ?');
    }
    /**
     * Operation updateSupplierRate
     *
     * Update an existing supplier_rate.
     *
     *
     * @return Http response
     */
    public function updateSupplierRate()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['body'])) {
            throw new \InvalidArgumentException('Missing the required parameter $body when calling updateSupplierRate');
        }
        $body = $input['body'];


        return response('How about implementing updateSupplierRate as a PUT method ?');
    }
    /**
     * Operation deleteSupplierRate
     *
     * Deletes an supplier_rate.
     *
     * @param int $supplier_rate_id supplier_rate id to delete (required)
     *
     * @return Http response
     */
    public function deleteSupplierRate($supplier_rate_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing deleteSupplierRate as a DELETE method ?');
    }
    /**
     * Operation getSupplierRateById
     *
     * Find supplier_rate by ID.
     *
     * @param int $supplier_rate_id ID of supplier_rate to return object (required)
     *
     * @return Http response
     */
    public function getSupplierRateById($supplier_rate_id)
    {
        $input = Request::all();

        //path params validation


        //not path params validation

        return response('How about implementing getSupplierRateById as a GET method ?');
    }
    /**
     * Operation supplierRatesGet
     *
     * supplier_rates List.
     *
     *
     * @return Http response
     */
    public function supplierRatesGet()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        $supplier_rate_id = $input['supplier_rate_id'];


        return response('How about implementing supplierRatesGet as a GET method ?');
    }
}
